# theme = "dracula"
theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
auto-save = true
idle-timeout = 0
# completion-replace = true
bufferline = "always"
color-modes = true

[editor.statusline]
left = ["mode", "spinner", "spacer", "diagnostics"]
right = ["file-encoding", "spacer", "position-percentage", "spacer", "position"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[keys.normal]
A-q = ":quit"
A-w = ":write"

[keys.normal.space]
A-q = ":buffer-close"
