theme = "dracula"

[editor]
line-number = "relative"
# auto-format = false
auto-save = true
idle-timeout = 0
completion-replace = true
bufferline = "always"
color-modes = true

[editor.statusline]
left = ["mode", "spinner", "spacer", "diagnostics"]
right = ["file-encoding", "spacer", "position-percentage", "spacer", "position"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[keys.normal]
A-q = ":quit"
# A-w = [":fmt", ":write"]
A-w = ":write"
