[[language]]
name = "bash"
auto-format = true
indent = { unit = "  ", tab-width = 2 }
formatter = { command = "shfmt", args = ["-i", "2"] }


[[language]]
name = "c"
auto-format = true


[[language]]
name = "cpp"
auto-format = true


[[language]]
name = "css"
formatter = { command = "prettierd", args = [".css"] }


[[language]]
name = "fish"
auto-format = true
formatter = { command = "fish_indent" }


[[language]]
name = "html"
formatter = { command = "prettierd", args = [".html"] }


[[language]]
name = "java"
auto-format = true


[[language]]
name = "javascript"
auto-format = true
formatter = { command = "prettierd", args = [".js"] }


[[language]]
name = "json"
formatter = { command = "prettierd", args = [".json"] }


[[language]]
name = "jsx"
auto-format = true
formatter = { command = "prettierd", args = [".jsx"] }


[[language]]
name = "lua"
auto-format = true
indent = { tab-width = 3, unit = "   " }
formatter = { command = "stylua", args = ["-"] }


[[language]]
name = "markdown"
auto-format = true
formatter = { command = "prettierd", args = [".md"] }


[[language]]
name = "nix"
auto-format = true
formatter = { command = "alejandra" }


[[language]]
name = "python"
auto-format = true
language-servers = ["pyright"]
formatter = { command = "ruff", args = ["format", "-"] }

[language-server.pyright]
command = "pyright-langserver"


[[language]]
name = "rust"
auto-format = true


[[language]]
name = "scss"
formatter = { command = "prettierd", args = [".scss"] }


[[language]]
name = "svelte"
auto-format = true
# formatter = { command = "prettierd", args = [".svelte"] }


[[language]]
name = "toml"
file-types = ["toml", "conf"]
auto-format = true
formatter = { command = "taplo", args = ["format", "-"] }


[[language]]
name = "tsx"
auto-format = true
formatter = { command = "prettierd", args = [".tsx"] }


[[language]]
name = "typescript"
auto-format = true
formatter = { command = "prettierd", args = [".ts"] }


[[language]]
name = "yaml"
auto-format = true
formatter = { command = "prettierd", args = [".yaml"] }
