[[language]]
name = "bash"
auto-format = true
indent = { tab-width = 2, unit = "  " }
formatter = { command = 'shfmt', args = ["-i", "2"] }

[[language]]
name = "c"
auto-format = true

[[language]]
name = "css"
formatter = { command = "prettierd", args = [".css"] }

[[language]]
name = "fish"
auto-format = true
formatter = { command = "fish_indent" }

[[language]]
name = "html"
formatter = { command = "prettierd", args = [".html"] }

[[language]]
name = "java"
auto-format = true

[[language]]
name = "javascript"
auto-format = true
formatter = { command = "deno", args = ["fmt", "-", "--ext", "js"] }
# formatter = { command = "prettierd", args = [".js"] }

[[language]]
name = "json"
formatter = { command = "deno", args = ["fmt", "-", "--ext", "json"] }
# formatter = { command = "prettierd", args = [".json"] }

[[language]]
name = "lua"
auto-format = true
formatter = { command = "stylua", args = ["-"] }

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "deno", args = ["fmt", "-", "--ext", "md"] }
# formatter = { command = "prettierd", args = [".md"] }

[[language]]
name = "python"
roots = ["pyproject.toml"]
auto-format = true
language-server = { command = "pyright-langserver", args = ["--stdio"] }
config = {}
formatter = { command = "black", args = ["--quiet", "-"] }

[[language]]
name = "rust"
auto-format = true
formatter = { command = "rustfmt" }

[[language]]
name = "scss"
formatter = { command = "prettierd", args = [".scss"] }

[[language]]
name = "svelte"
auto-format = true
# formatter = { command = "prettierd", args = [".svelte"] }

[[language]]
name = "toml"
file-types = ["toml", "conf"]
auto-format = true
formatter = { command = "taplo", args = ["format", "-"] }

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "deno", args = ["fmt", "-", "--ext", "ts"] }
# formatter = { command = "prettierd", args = [".ts"] }

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "prettierd", args = [".yaml"] }
