#!/usr/bin/env bash

ln -sf ~/.local/dotfiles/binkctl ~/.local/binkctl
ln -sf ~/.local/dotfiles/config/chrome/chrome-flags.conf ~/.config/chrome-flags.conf
ln -sf ~/.local/dotfiles/config/code/code-flags.conf ~/.config/code-flags.conf
ln -sf ~/.local/dotfiles/config/electron/electron-flags.conf ~/.config/electron-flags.conf
ln -sf ~/.local/dotfiles/config/eww ~/.config/eww
ln -sf ~/.local/dotfiles/config/hypr ~/.config/hypr
ln -sf ~/.local/dotfiles/config/kitty ~/.config/kitty
ln -sf ~/.local/dotfiles/config/nvim ~/.config/nvim
ln -sf ~/.local/dotfiles/config/paru ~/.config/paru
ln -sf ~/.local/dotfiles/config/starship/starship.toml ~/.config/starship.toml
ln -sf ~/.local/dotfiles/config/tmux ~/.config/tmux
ln -sf ~/.local/dotfiles/config/zsh/.zshrc ~/.zshrc
