"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Asqar Arslanov"
email = "asqarslanov@gmail.com"

[ui]
default-command = "log"

[git]
private-commits = '''description(glob:'private:*')'''
