[[manager.prepend_keymap]]
on = "T"
run = "plugin max-preview"
desc = "Maximize or restore preview"

[[manager.prepend_keymap]]
on = ["<C-n>"]
run = '''
shell 'ripdrag "$@" -x 2>/dev/null &' --confirm
'''
