[Terminal]
command = "kitty"
launch-delay-seconds = 0.5
lazy = false
window-class = "kitty"

[Chat]
command = "flatpak"
arguments = ["run", "org.telegram.desktop"]
launch-delay-seconds = 0.5
lazy = false
window-class = "org.telegram.desktop"

[GUI-File-Manager]
command = "nemo"
launch-delay-seconds = 0.5
lazy = false
window-class = "nemo"
