#!/usr/bin/env python3

import json
import sys

import sysinteraction

if __name__ == '__main__':
    if len(sys.argv) > 2:
        sysinteraction.exit_with_error()

    length_limit = None

    if len(sys.argv) == 2:
        if not sys.argv[1].isdecimal():
            sysinteraction.exit_with_error()

        length_limit = int(sys.argv[1])

    command = 'hyprctl activewindow -j'
    active_window_info_raw = sysinteraction.get_command_output(command)

    active_window_info = json.loads(active_window_info_raw)

    if not active_window_info:
        exit()

    active_window_title = active_window_info['title']

    if length_limit is not None and len(active_window_title) > length_limit:
        active_window_title = active_window_title[: length_limit - 1] + "…"

    print(active_window_title)
