#!/usr/bin/env python3

import sys

import sysinteraction

VARIABLE_NAME = 'show-bar'

if __name__ == '__main__':
    if len(sys.argv) != 2:
        sysinteraction.exit_with_error()

    action = sys.argv[1]

    match action:
        case 'off':
            flag = True

        case 'on':
            flag = False

        case 'toggle':
            flag = sysinteraction.read_variable(VARIABLE_NAME)

        case _:
            sysinteraction.exit_with_error()

    if flag:
        command = 'eww close bar'
    else:
        command = 'eww open bar'

    sysinteraction.execute(command)
    sysinteraction.write_variable(VARIABLE_NAME, not flag)
    sysinteraction.print_success_message()
