# v2.7.*

backend = "fastresize"
color_space = "labfast"
threshold = 20
filter = "dark16"

[[entry]]
template = "templates/colors"
target = "~/.cache/wal/colors"

[[entry]]
template = "templates/colors.css"
target = "~/.cache/wal/colors.css"

[[entry]]
template = "templates/colors.json"
target = "~/.cache/wal/colors.json"

[[entry]]
template = "templates/colors.lua"
target = "~/.cache/wal/colors.lua"

[[entry]]
template = "templates/colors.ron"
target = "~/.cache/wal/colors.ron"

[[entry]]
template = "templates/colors.scss"
target = "~/.cache/wal/colors.scss"

[[entry]]
template = "templates/colors.sh"
target = "~/.cache/wal/colors.sh"

[[entry]]
template = "templates/colors.toml"
target = "~/.cache/wal/colors.toml"

[[entry]]
template = "templates/colors.yaml"
target = "~/.cache/wal/colors.yaml"

[[entry]]
template = "templates/gtk.css"
target = "~/.cache/wal/gtk.css"

[[entry]]
template = "templates/hyprland.conf"
target = "~/.cache/wal/hyprland.conf"

[[entry]]
template = "templates/kitty.conf"
target = "~/.cache/wal/kitty.conf"

[[entry]]
template = "templates/tty.sh"
target = "~/.cache/wal/tty.sh"
