[templates]
css = { src = "colors.css", dst = "~/.cache/wal/colors.css" }
ghostty = { src = "ghostty", dst = "~/.cache/wal/ghostty" }
gtk = { src = "gtk.css", dst = "~/.cache/wal/gtk.css" }
hyprland = { src = "hyprland.conf", dst = "~/.cache/wal/hyprland.conf" }
json = { src = "colors.json", dst = "~/.cache/wal/colors.json" }
kitty = { src = "kitty.conf", dst = "~/.cache/wal/kitty.conf" }
lua = { src = "colors.lua", dst = "~/.cache/wal/colors.lua" }
plain = { src = "colors", dst = "~/.cache/wal/colors" }
ron = { src = "colors.ron", dst = "~/.cache/wal/colors.ron" }
scss = { src = "colors.scss", dst = "~/.cache/wal/colors.scss" }
sh = { src = "colors.sh", dst = "~/.cache/wal/colors.sh" }
toml = { src = "colors.toml", dst = "~/.cache/wal/colors.toml" }
tty = { src = "tty.sh", dst = "~/.cache/wal/tty.sh" }
yaml = { src = "colors.yaml", dst = "~/.cache/wal/colors.yaml" }
