window-padding-x = 8
window-padding-y = 8
window-theme = "ghostty"

adjust-cursor-thickness = 3

# focus-follows-mouse = true
# show_hyperlink_targets yes
# confirm_os_window_close 0
# cursor-trail = 3

gtk-single-instance = true
gtk-titlebar = false
gtk-tabs-location = "bottom"
gtk-wide-tabs = false
