[Terminal]
command = "kitty"
launch-delay-seconds = 0.5
window-class = "kitty"

[File-Manager]
command = "nemo"
launch-delay-seconds = 0.5
window-class = "nemo"

[Authy]
command = "flatpak"
arguments = ["run", "com.authy.Authy"]
launch-delay-seconds = 10
lazy = false
window-class = "Authy Desktop"
