[character]
success_symbol = '[\$](green)'
error_symbol = '[\$](red)'
vimcmd_symbol = '[<](bold blue)'
vimcmd_replace_one_symbol = '[<](bold purple)'
vimcmd_replace_symbol = '[<](bold purple)'
vimcmd_visual_symbol = '[<](bold yellow)'
