[Terminal]
command = "kitty"
launch-delay-seconds = 0.5
lazy = false
window-class = "kitty"

[Chat]
command = "telegram-desktop"
launch-delay-seconds = 2
lazy = false
window-class = "org.telegram.desktop"
