#!/usr/bin/env sh

echo it was $XKB_LAYOUT
export XKB_LAYOUT=test
echo now it is $XKB_LAYOUT

# if [ $XKB_LAYOUT == 'us' ]
# then
    # # hyprctl keyword input:kb_layout ru
    # export XKB_LAYOUT=ru
    # echo "On us to ru"
# else
    # # hyprctl keyword input:kb_layout us
    # export XKB_LAYOUT=us
    # echo "On ru to us"
# fi
