#!/usr/bin/env python3

import os
import subprocess


layout_file_path = f'/home/{os.getlogin()}/.vars/xkb-layout'

with open(layout_file_path) as layout_file:
    layout = layout_file.read()

if layout == 'us':
    layout = 'ru'
else:
    layout = 'us'

with open(layout_file_path, 'w') as layout_file:
    layout_file.write(layout)
