#!/usr/bin/env python3

import os
import shutil

DEFAULT_VARIABLES = {
    # true, false
    'opaque-inactive-windows': 'true',

    # us, ru
    'xkb-layout': 'us'
}


base_dir = f'/home/{os.getlogin()}/.vars'

if os.path.isfile(base_dir):
    os.remove(base_dir)
elif os.path.isdir(base_dir):
    shutil.rmtree(base_dir)

os.mkdir(base_dir)

for key, value in DEFAULT_VARIABLES.items():
    with open(f'{base_dir}/{key}', 'w') as destination_file:
        destination_file.write(str(value))
