#!/usr/bin/env python3

import datetime


def get_current_time() -> str:
    now = datetime.datetime.now()

    hour = now.strftime('%I').lstrip('0')
    minute = now.strftime('%M')
    noon_flag = now.strftime('%p')

    return f"{hour}:{minute} {noon_flag}"


current_time = get_current_time()
print(current_time)
