#!/usr/bin/env python3

import sysinteraction

VARIABLE_NAME = 'use-gaps'

flag = sysinteraction.read_variable(VARIABLE_NAME)

if flag:
    gaps_in = 0
    gaps_out = 0
    rounding = 0
else:
    gaps_in = 6
    gaps_out = 24
    rounding = 16

commands = (
    f'hyprctl keyword general:gaps_in {gaps_in}',
    f'hyprctl keyword general:gaps_out {gaps_out}',
    f'hyprctl keyword windowrulev2 rounding {rounding} floating: 0',
)

for command in commands:
    sysinteraction.execute(command)

sysinteraction.write_variable(VARIABLE_NAME, not flag)
