#!/usr/bin/env python3

import sysinteraction

VARIABLE_NAME = 'show-bar'

flag = sysinteraction.read_variable(VARIABLE_NAME)

if flag:
    command = 'eww close bar'
else:
    command = 'eww open bar'

sysinteraction.execute(command)

sysinteraction.write_variable(VARIABLE_NAME, not flag)
