#!/usr/bin/env python3

import sysinteraction

DEFAULT_VARIABLES = {
    # true, false
    'opaque-inactive': 'true',

    # true, false
    'show-bar': 'true',

    # false, true
    'use-gaps': 'false',

    # us, ru
    'xkb-layout': 'US'
}

sysinteraction.update_directory(sysinteraction.variable_directory)

for key, value in DEFAULT_VARIABLES.items():
    sysinteraction.write_variable(key, value)
