#!/usr/bin/env python3

import sysinteraction

VARIABLE_NAME = 'xkb-layout'

layout = sysinteraction.read_variable(VARIABLE_NAME)

if layout == 'us':
    sysinteraction.write_variable(VARIABLE_NAME, 'ru')
else:
    sysinteraction.write_variable(VARIABLE_NAME, 'us')
