#!/usr/bin/env python3

import json

import sysinteraction

command = 'hyprctl activewindow -j'
active_window_info_raw = sysinteraction.get_command_output(command)

active_window_info = json.loads(active_window_info_raw)
active_window_title = active_window_info['title']

if len(active_window_title) > 48:
    active_window_title = active_window_title[:47] + "…"

print(active_window_title)
