#!/usr/bin/env python3

import os
import subprocess


def set_hyprland_inactive_opacity(value: float) -> None:
    command = f'hyprctl keyword decoration:inactive_opacity {value}'

    arguments = command.split()
    subprocess.run(arguments)


flag_file_path = f'/home/{os.getlogin()}/.vars/opaque-inactive'

with open(flag_file_path) as flag_file:
    flag = flag_file.read()

if flag == 'true':
    set_hyprland_inactive_opacity(1)
    flag = 'false'
else:
    set_hyprland_inactive_opacity(0.75)
    flag = 'true'

with open(flag_file_path, 'w') as flag_file:
    flag_file.write(flag)
