#!/usr/bin/env python3

"""
This script is made for changing screen brightness in accordance
with human perception.

The `brightnessctl` package is assumed to be installed.

In the code, all values and steps in the variable names refer
to screen brightness values and screen brightness steps, respectively.

Made by Askar Arslanov (@AskarBink) thanks to Konrad Strack.
"""

import math
import subprocess
import sys
import typing

STEPS = 11


def get_command_output(command: str) -> str:
    arguments = command.split()
    process = subprocess.run(arguments, capture_output=True, text=True)

    result: str = process.stdout

    return result


def get_current_value() -> int:
    command = "brightnessctl g"
    output = get_command_output(command)

    result = int(output)

    return result


def get_max_value() -> int:
    command = "brightnessctl m"
    output = get_command_output(command)
    result = int(output)

    return result


def set_value(value: int) -> None:
    command = f"brightnessctl s {value}"

    arguments = command.split()
    subprocess.run(arguments, stdout=subprocess.DEVNULL)


def step_to_value(step: int, steps: int, min_value: int, max_value: int) -> int:
    x_min = math.log10(min_value)
    x_max = math.log10(max_value)

    x = step / steps * (x_max - x_min)

    result = round(10**x)

    return result


def value_to_step(value: int, steps: int, min_value: int, max_value: int) -> int:
    x_min = math.log10(min_value)
    x_max = math.log10(max_value)

    x = math.log10(value) / (x_max - x_min)

    result = round(steps * x)

    return result


def get_nearest_index(
    sequence: typing.Sequence[typing.SupportsFloat],
    value: typing.SupportsFloat,
    preference: typing.Literal["less", "greater"] = None,
) -> int:
    """
    Returns the index of the closest to `value` element in `sequence`
    with taking `preference` into account
    (can be either `'less'` or `'greater'`, defaults to `None`).

    The binary search algorithm is used.
    """

    left = 0
    right = len(sequence)

    while right - left > 1:
        middle = (left + right) // 2

        if sequence[middle] <= value:
            left = middle
        else:
            right = middle

    if right == len(sequence):
        return left

    if sequence[left] == value:
        return left

    match preference:
        case "less":
            return left
        case "greater":
            return right

    if abs(value - sequence[left]) < abs(value - sequence[right]):
        return left
    else:
        return right


def generate_step_values(steps: int, min_value: int, max_value: int) -> list:
    """
    Returns a list with brightness values for each step.
    """

    max_step = value_to_step(max_value, STEPS, min_value, max_value)

    step_values = steps * [None]

    step_values[0] = min_value
    step_values[-1] = max_value

    for i in range(1, STEPS - 1):
        step_values[STEPS - i - 1] = step_to_value(
            max_step - i, STEPS, min_value, max_value
        )

    return step_values


def get_percent_by_step(step: int, steps: int) -> int:
    """
    Returns the brightness percentage for the given step.
    Never reaches 0, returns 1 instead.
    """

    percent = 100 * (step - 1) / (steps - 1)

    result = round(percent)

    if result == 0:
        return 1

    return result


if __name__ == "__main__":
    if len(sys.argv) != 2 or sys.argv[1] not in ("-", "+", "%"):
        print(
            "Usage:\n"
            "  brightness [operation]\n"
            "\n"
            "Operations:\n"
            "  -\tdecrease brightness.\n"
            "  +\tincrease brightness.\n"
            "  %\tget current brightness.\n"
        )

        sys.exit(-1)

    operation = sys.argv[1]

    max_value = get_max_value()
    min_value = round(0.01 * max_value)

    step_values = generate_step_values(STEPS, min_value, max_value)

    current_value = get_current_value()

    match operation:
        case "decrease":
            current_step = get_nearest_index(step_values, current_value, "greater")

            if current_step == 0:
                new_step = 0
            else:
                new_step = current_step - 1

        case "increase":
            current_step = get_nearest_index(step_values, current_value, "less")

            if current_step == STEPS - 1:
                new_step = STEPS - 1
            else:
                new_step = current_step + 1

        case "get":
            current_step = get_nearest_index(step_values, current_value)

            new_step = current_step

            percent = get_percent_by_step(new_step + 1, STEPS)
            print(percent)

    new_value = step_values[new_step]
    set_value(new_value)
