#!/usr/bin/env python3

import json
import sys
import typing

import sysinteraction


def trim(string: str, length_limit: typing.Union[int, None]) -> str:
    if length_limit is None:
        return string

    if len(string) > length_limit:
        string = string[: length_limit - 1] + "…"
        # string = "…" + string[-1 * (length_limit - 1):]

    return string


if __name__ == "__main__":
    if len(sys.argv) > 2:
        sysinteraction.exit_with_error()

    length_limit = None

    if len(sys.argv) == 2:
        if not sys.argv[1].isdecimal():
            sysinteraction.exit_with_error()

        length_limit = int(sys.argv[1])

    command = "hyprctl -j activewindow"
    active_window_info_raw = sysinteraction.get_command_output(command)

    active_window_info = json.loads(active_window_info_raw)

    if not active_window_info:
        exit()

    active_window_title = active_window_info["title"]
    active_window_title = trim(active_window_title, length_limit)

    print(active_window_title)
