#!/usr/bin/env python3

import sys

import sysinteraction

VARIABLE_NAME = "show-bar"

if __name__ == "__main__":
    flag = False

    if len(sys.argv) > 2:
        sysinteraction.exit_with_error()

    if len(sys.argv) == 1:
        flag = sysinteraction.read_variable(VARIABLE_NAME)

    elif len(sys.argv) == 2:
        action = sys.argv[1]

        match action:
            case "on":
                flag = False
            case "off":
                flag = True
            case _:
                sysinteraction.exit_with_error()

    if flag:
        command = "eww close bar"
    else:
        command = "eww open bar"

    sysinteraction.execute(command)
    sysinteraction.write_variable(VARIABLE_NAME, not flag)
    sysinteraction.print_success_message()
