#!/usr/bin/env python3

import datetime
import sys

import sysinteraction

if __name__ == "__main__":
    if len(sys.argv) != 1:
        sysinteraction.exit_with_error()

    now = datetime.datetime.now()

    weekday = now.strftime("%a")
    month = now.strftime("%b")
    day = now.strftime("%d").lstrip("0")

    current_date = f"{weekday} {month} {day}"

    print(current_date)
