#!/usr/bin/env python3

import sys

import sysinteraction

variables = {
    # True, False
    'change-opacity': True,

    # 0, 1, 2
    'gaps-level': 0,

    # 'En', 'Ru'
    'keyboard-layout': 'En',

    # None, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
    'previous-workspace': None,

    # True, False
    'show-bar': True
}

if __name__ == '__main__':
    arguments = sys.argv[1:]

    for i in arguments:
        try:
            key, value = i.split('=')
        except BaseException:
            sysinteraction.reload_system()

        variables[key] = value

    sysinteraction.update_directory(sysinteraction.vars_directory)

    for key, value in variables.items():
        try:
            sysinteraction.write_variable(key, value)
        except BaseException:
            sysinteraction.reload_system()

    sysinteraction.print_success_message()
