#!/usr/bin/env python3

import sys

import sysinteraction

VARIABLE_NAME = "change-opacity"

if __name__ == "__main__":
    flag = False

    if len(sys.argv) > 2:
        sysinteraction.exit_with_error()

    if len(sys.argv) == 1:
        flag = sysinteraction.read_variable(VARIABLE_NAME)

    elif len(sys.argv) == 2:
        action = sys.argv[1]

        match action:
            case "on":
                flag = False
            case "off":
                flag = True
            case _:
                sysinteraction.exit_with_error()

    if flag:
        opacity_value = 1
    else:
        opacity_value = 0.75

    keyword = "decoration:inactive_opacity"
    sysinteraction.set_keyword(keyword, opacity_value)

    sysinteraction.write_variable(VARIABLE_NAME, not flag)
    sysinteraction.print_success_message()
