#!/usr/bin/env python3

import json

import sysinteraction

if __name__ == '__main__':
    workspaces = []

    for i in range(1, 11):
        workspace = {
            'id': i,
            'name': str(i),
            'occupied': False,
            'hasfullscreen': False,
            'previous': False
        }
        workspaces.append(workspace)

    workspaces[9]['name'] = "0"

    command = 'hyprctl -j workspaces'
    workspaces_raw_str = sysinteraction.get_command_output(command)
    workspaces_raw = json.loads(workspaces_raw_str)

    for workspace in workspaces_raw:
        workspace_id = workspace['id'] - 1

        workspaces[workspace_id]['occupied'] = workspace['windows'] > 0
        workspaces[workspace_id]['hasfullscreen'] = workspace['hasfullscreen']

    print(workspaces)
